version: '2'
services:
  contacts-app:
    image: ghacupha/contacts-app:0.0.1-SNAPSHOT
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://contacts-postgresql:5432/contacts
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://contacts-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://contacts-elasticsearch:9200
      - PG_DATABASE_DEV_USER=${PG_DATABASE_DEV_USER}
      - PG_DATABASE_DEV_PASSWORD=${PG_DATABASE_DEV_PASSWORD}
    ports:
      - 8980:8980
  contacts-postgresql:
    extends:
      file: postgresql.yml
      service: contacts-postgresql
  contacts-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: contacts-elasticsearch
